#!/bin/bash


if [ "$1" = "--newday" ]; then
    currentDay="day$2"

    mkdir $currentDay
    cp ./.template/day.py ./$currentDay/"$currentDay.py"
    cp ./.template/input.txt ./$currentDay/input.txt
else
    currentDay="day$1"
    python $currentDay/"$currentDay.py"
fi